let currentActivity=null, risks=[], editingIndex=null;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[s]));
async function loadActivity(id){const r=await fetch(`/api/activity/${id}`);const d=await r.json();currentActivity=d.activity;risks=d.risks.map(x=>({...x,userLimit:x.defaultLimit,userNote:x.clientNote||""}));renderActivity();renderRisks();renderSummary();}
function renderActivity(){$("activityInfo").innerHTML=`<div style="display:flex;justify-content:space-between;gap:18px;align-items:flex-start"><div><h3>${esc(currentActivity.name)}</h3><p>${esc(currentActivity.summary)}</p><p style="margin-top:14px"><strong>Orientační limit:</strong> ${esc(currentActivity.limitHint)}</p></div><span class="risk-level">Rizikovost: ${esc(currentActivity.riskLevel)}</span></div>`}
function renderRisks(){$("riskGrid").innerHTML=risks.map((r,i)=>`<article class="risk-card ${r.active?"":"inactive"}" data-index="${i}"><div class="card-top"><h3>${esc(r.name)}</h3><span class="pill">${esc(r.priority||"VLASTNÍ")}</span></div><p>${esc(r.explanation)}</p><div class="limit">Limit: ${esc(r.userLimit||r.defaultLimit||"doplnit")}</div>${r.active?"":'<div class="limit">Vyřazeno z poptávky</div>'}</article>`).join("");document.querySelectorAll(".risk-card").forEach(c=>c.addEventListener("click",()=>openModal(Number(c.dataset.index))))}
function openModal(i){editingIndex=i;const r=risks[i];$("modalTitle").textContent=r.name||"Vlastní riziko";$("modalPriority").textContent=r.priority||"VLASTNÍ";$("riskActive").checked=!!r.active;$("riskName").value=r.name||"";$("riskLimit").value=r.userLimit||r.defaultLimit||"";$("riskQuestion").value=r.clientQuestion||"";$("riskExplanation").value=r.explanation||"";$("riskClientNote").value=r.userNote||r.clientNote||"";$("riskRecommendation").value=r.recommendation||"";$("modalOverlay").classList.remove("hidden")}
function closeModal(){$("modalOverlay").classList.add("hidden");editingIndex=null}
function saveRisk(){if(editingIndex===null)return;let r=risks[editingIndex];r.active=$("riskActive").checked;r.name=$("riskName").value.trim()||"Vlastní riziko";r.userLimit=$("riskLimit").value.trim();r.clientQuestion=$("riskQuestion").value.trim();r.explanation=$("riskExplanation").value.trim();r.userNote=$("riskClientNote").value.trim();r.recommendation=$("riskRecommendation").value.trim();renderRisks();renderSummary();closeModal()}
function deleteRisk(){if(editingIndex===null)return;risks.splice(editingIndex,1);renderRisks();renderSummary();closeModal()}
function addCustomRisk(){risks.push({id:"custom_"+Date.now(),name:"Nové vlastní riziko",priority:"VLASTNÍ",active:true,defaultLimit:"",userLimit:"",clientQuestion:"Doplňte otázku pro klienta.",explanation:"Doplňte vysvětlení rizika pro poradce.",userNote:"",recommendation:""});renderRisks();openModal(risks.length-1)}
function renderSummary(){const active=risks.filter(r=>r.active),inactive=risks.filter(r=>!r.active),lines=[];lines.push("ASTORIE – pracovní podklad k poptávce podnikatelského pojištění","");if(currentActivity){lines.push(`Činnost klienta: ${currentActivity.name}`,`Profil činnosti: ${currentActivity.summary}`,`Orientační limit dle profilu: ${currentActivity.limitHint}`)}lines.push("","Doporučená / potvrzená rizika:");active.forEach((r,i)=>{lines.push(`${i+1}. ${r.name} – limit/sublimit: ${r.userLimit||r.defaultLimit||"doplnit"}`);const note=r.userNote||r.clientNote;if(note)lines.push(`   Poznámka: ${note}`);if(r.recommendation)lines.push(`   Důvod: ${r.recommendation}`)});if(inactive.length){lines.push("","Rizika odebraná poradcem / klientem:");inactive.forEach((r,i)=>lines.push(`${i+1}. ${r.name}`))}lines.push("","Poznámka: Návrhy limitů jsou orientační odbornou pomůckou. Konečné nastavení musí odpovídat požadavkům, potřebám a rizikovému profilu klienta.");$("summaryBox").value=lines.join("\n")}
$("activitySelect").addEventListener("change",e=>loadActivity(e.target.value));$("addRiskBtn").addEventListener("click",addCustomRisk);$("saveRiskBtn").addEventListener("click",saveRisk);$("deleteRiskBtn").addEventListener("click",deleteRisk);$("cancelModalBtn").addEventListener("click",closeModal);$("closeModalBtn").addEventListener("click",closeModal);$("modalOverlay").addEventListener("click",e=>{if(e.target===$("modalOverlay"))closeModal()});$("copySummaryBtn").addEventListener("click",async()=>{await navigator.clipboard.writeText($("summaryBox").value);alert("Text byl zkopírován do schránky.")});loadActivity($("activitySelect").value);